---

- name: Distribute scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    mode: "0555"
  loop:
    - duplicity.sh
    - functions.sh

- name: Setup backup location
  ansible.builtin.file:
    path: "{{ duplicity_backup_location }}"
    state: directory
    owner: root
    group: "{{ backup_group }}"
    mode: "2750"
  when: duplicity_backup_location is defined
